-- 升级到 40 道题版本（4 维度 × 10 题）
-- 旧表只有 20 题 / 1 条测试数据，丢弃后重建
DROP TABLE IF EXISTS submissions;

CREATE TABLE submissions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  service_date TEXT NOT NULL,                -- YYYY-MM-DD
  caregiver_name TEXT NOT NULL,

  -- 一、专业性（Q1-Q10）
  q1  INTEGER NOT NULL CHECK (q1  BETWEEN 1 AND 5),
  q2  INTEGER NOT NULL CHECK (q2  BETWEEN 1 AND 5),
  q3  INTEGER NOT NULL CHECK (q3  BETWEEN 1 AND 5),
  q4  INTEGER NOT NULL CHECK (q4  BETWEEN 1 AND 5),
  q5  INTEGER NOT NULL CHECK (q5  BETWEEN 1 AND 5),
  q6  INTEGER NOT NULL CHECK (q6  BETWEEN 1 AND 5),
  q7  INTEGER NOT NULL CHECK (q7  BETWEEN 1 AND 5),
  q8  INTEGER NOT NULL CHECK (q8  BETWEEN 1 AND 5),
  q9  INTEGER NOT NULL CHECK (q9  BETWEEN 1 AND 5),
  q10 INTEGER NOT NULL CHECK (q10 BETWEEN 1 AND 5),

  -- 二、服务态度（Q11-Q20）
  q11 INTEGER NOT NULL CHECK (q11 BETWEEN 1 AND 5),
  q12 INTEGER NOT NULL CHECK (q12 BETWEEN 1 AND 5),
  q13 INTEGER NOT NULL CHECK (q13 BETWEEN 1 AND 5),
  q14 INTEGER NOT NULL CHECK (q14 BETWEEN 1 AND 5),
  q15 INTEGER NOT NULL CHECK (q15 BETWEEN 1 AND 5),
  q16 INTEGER NOT NULL CHECK (q16 BETWEEN 1 AND 5),
  q17 INTEGER NOT NULL CHECK (q17 BETWEEN 1 AND 5),
  q18 INTEGER NOT NULL CHECK (q18 BETWEEN 1 AND 5),
  q19 INTEGER NOT NULL CHECK (q19 BETWEEN 1 AND 5),
  q20 INTEGER NOT NULL CHECK (q20 BETWEEN 1 AND 5),

  -- 三、服务效率（Q21-Q30）
  q21 INTEGER NOT NULL CHECK (q21 BETWEEN 1 AND 5),
  q22 INTEGER NOT NULL CHECK (q22 BETWEEN 1 AND 5),
  q23 INTEGER NOT NULL CHECK (q23 BETWEEN 1 AND 5),
  q24 INTEGER NOT NULL CHECK (q24 BETWEEN 1 AND 5),
  q25 INTEGER NOT NULL CHECK (q25 BETWEEN 1 AND 5),
  q26 INTEGER NOT NULL CHECK (q26 BETWEEN 1 AND 5),
  q27 INTEGER NOT NULL CHECK (q27 BETWEEN 1 AND 5),
  q28 INTEGER NOT NULL CHECK (q28 BETWEEN 1 AND 5),
  q29 INTEGER NOT NULL CHECK (q29 BETWEEN 1 AND 5),
  q30 INTEGER NOT NULL CHECK (q30 BETWEEN 1 AND 5),

  -- 四、情感体验（Q31-Q40）
  q31 INTEGER NOT NULL CHECK (q31 BETWEEN 1 AND 5),
  q32 INTEGER NOT NULL CHECK (q32 BETWEEN 1 AND 5),
  q33 INTEGER NOT NULL CHECK (q33 BETWEEN 1 AND 5),
  q34 INTEGER NOT NULL CHECK (q34 BETWEEN 1 AND 5),
  q35 INTEGER NOT NULL CHECK (q35 BETWEEN 1 AND 5),
  q36 INTEGER NOT NULL CHECK (q36 BETWEEN 1 AND 5),
  q37 INTEGER NOT NULL CHECK (q37 BETWEEN 1 AND 5),
  q38 INTEGER NOT NULL CHECK (q38 BETWEEN 1 AND 5),
  q39 INTEGER NOT NULL CHECK (q39 BETWEEN 1 AND 5),
  q40 INTEGER NOT NULL CHECK (q40 BETWEEN 1 AND 5),

  -- 4 维度均分（每维度 10 题，提交时计算并冗余存储）
  professionalism REAL NOT NULL,             -- Q1-Q10 均分
  attitude        REAL NOT NULL,             -- Q11-Q20 均分
  efficiency      REAL NOT NULL,             -- Q21-Q30 均分
  emotion         REAL NOT NULL,             -- Q31-Q40 均分
  total_score     REAL NOT NULL,             -- 4 维度均值的均值

  user_agent TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_submissions_created_at   ON submissions(created_at);
CREATE INDEX idx_submissions_caregiver    ON submissions(caregiver_name);
CREATE INDEX idx_submissions_service_date ON submissions(service_date);
CREATE INDEX idx_submissions_phone        ON submissions(customer_phone);
